version: '3.9'

services:  
  websocket-service:
    container_name: websocket-gateway
    build: .
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "4444:4444"
    networks:
     - wegugin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  wegugin:
    external: true

   